version: '3.8'

services:
  dev:
    build:
      context: ./docker/dev
    volumes:
      - "stack:/stack_root"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - SLS_DEBUG=*
volumes:
  stack: